include:
  - project: pektin/pektin-dist
    ref: main
    file:
      - scripts/mirror.yml
      - scripts/docker-build-and-publish.yml

image: alpine

variables:
  IMAGE_NAME: ui

stages:
  - mirror
  - docker-build-and-publish
