include:
  - project: pektin/pektin-dist
    ref: main
    file:
      - scripts/docker-build-and-publish.yml

image: alpine

variables:
  IMAGE_NAME: ui

stages:
  - docker-build-and-publish

default:
  before_script:
    - sed -i "s|CI_COMMIT_SHORT_SHA|${1}|g" ./public/index.html
