image: node:latest

stages:
    - build
    - docker-build

build:
    stage: build
    script:
        - yarn
        - sed -i "s|CI_COMMIT_SHORT_SHA|$CI_COMMIT_SHORT_SHA|g" ./public/index.html
        - yarn build
    artifacts:
        expire_in: 1 hour
        paths:
            - build
            - nginx

docker-build:
    stage: docker-build
    image: docker:latest
    before_script:
        - export CI_REGISTRY=index.docker.io/v1/
        - docker login -u "pektin" -p "$CI_REGISTRY_PASSWORD" https://$CI_REGISTRY
    script:
        - docker build --pull -t "$CI_REGISTRY/$CI_PROJECT_NAME" .
        - docker push "$CI_REGISTRY/$CI_PROJECT_NAME"
