version: "3.7"
services:
    nginx:
        image: nginx:alpine
        volumes:
            - ../build:/usr/share/nginx/html
            - ../server/nginx.conf.template:/etc/nginx/templates/default.conf.template
        environment:
            - CSP_CONNECT_SRC=*
        ports:
            - 4002:80
